inherit_from: .rubocop_todo.yml

inherit_gem:
  bixby: bixby_default.yml


Layout/LineLength:
  Exclude:
    - spec/support/solr_documents/*

# Views do not have classes or modules
RSpec/DescribeClass:
  Exclude:
    - spec/views/**/*

RSpec/RepeatedExample:
  Exclude:
    - spec/system/access_restrictions_spec.rb
