inherit_from: .rubocop_todo.yml

inherit_gem:
  bixby: bixby_default.yml


Layout/LineLength:
  Exclude:
    - spec/support/solr_documents/*

# Views do not have classes or modules
RSpec/DescribeClass:
  Exclude:
    - spec/views/**/*
    - spec/system/search_result_pagination_spec.rb
    - spec/system/date_slider_spec.rb

RSpec/InstanceVariable:
  Exclude:
    - spec/helpers/blacklight_helper_spec.rb

RSpec/RepeatedExample:
  Exclude:
    - spec/system/access_restrictions_spec.rb
