version: '3.0'
services:
  web:
    image: yalelibraryit/dc-blacklight:105ac
    command: /bin/sh -c "cd /home/app/webapp && sleep 10 && rake yale:load_voyager_sample_data && /sbin/my_init"
    logging:
      driver: awslogs
      options:
        awslogs-group: mml
        awslogs-region: us-east-2
        awslogs-stream-prefix: web
    env_file:
      - .env_ecs
      - .secrets
    ports:
      - "3000:3000"
    volumes:
      - web:/home/app/webapp

  db:
    image: postgres
    env_file:
      - .env_ecs
    logging:
      driver: awslogs
      options:
        awslogs-group: mml
        awslogs-region: us-east-2
        awslogs-stream-prefix: db
    ports:
      - "5432:5432"
    volumes:
      - "db:/var/lib/postgresql/data"

  iiif_image:
    image: yalelibraryit/dc-iiif-cantaloupe:latest
    env_file:
      - .env_ecs
      - .secrets
    ports:
      - "8182:8182"
    logging:
      driver: awslogs
      options:
        awslogs-group: mml
        awslogs-region: us-east-2
        awslogs-stream-prefix: iiif_image

  solr:
    image: yalelibraryit/dc-solr:${SOLR_TAG}
    ports:
      - "8983:8983"
    logging:
      driver: awslogs
      options:
        awslogs-group: mml
        awslogs-region: us-east-2
        awslogs-stream-prefix: solr
    env_file:
      - .env_ecs
    command: bash -c "precreate-core ${SOLR_CORE} /opt/config && exec solr -f"

  iiif_manifest:
    image: yalelibraryit/dc-iiif-manifest:demo
    ports:
      - '80:80'
    logging:
      driver: awslogs
      options:
        awslogs-group: mml
        awslogs-region: us-east-2
        awslogs-stream-prefix: iiif_manifest

volumes:
  postgres:
  web:
  solr:
  db:
