abstract_tesim: 'Abstract'
alternativeTitle_tesim: 'Alternative Title'
description_tesim: 'Description'
extent_ssim: 'Extent'
extentOfDigitization_ssim: 'Extent of Digitization'
numberOfPages_ssim: 'Number of Pages'
illustrativeMatter_tesim: 'Illustrative Matter'
projection_tesim: 'Projection'
references_tesim: 'References'
scale_tesim: 'Scale'
subtitle_tesim: 'Subtitle'
subtitle_vern_tesim: 'Subtitle'