box_ssim: 'Box'
identifierShelfMark_ssim: 'Call Number'
children_ssim: 'Children'
partOf_ssim: 'Collection Name'
findingAid_ssim: 'Finding Aid'
folder_ssim: 'Folder'
identifierMfhd_ssim: 'Identifier MFHD'
importUrl_ssim: 'Import URL'
isbn_ssim: 'ISBN'
orbisBarcode_ssi: 'Orbis Bar Code'
orbisBibId_ssi: 'Orbis Bib ID'
oid_ssi: 'OID'
uri_ssim: 'URI'
url_fulltext_ssim: 'URL'
url_suppl_ssim: 'More Information'
