format: 'Format'
genre_ssim: 'Genre'
geoSubject_ssim: 'Subject (Geographic)'
material_tesim: 'Material'
resourceType_ssim: 'Resource Type'
subjectName_ssim: 'Subject (Name)'
subjectTopic_tesim: 'Subject (Topic)'
