# frozen_string_literal: true
ADVANCED_SEARCH_TESTING_1 = {
  "id": "1",
  "abstract_tesim": ["Incomplete at beginning and end.",
                     "The tale of Sindbād and his princely pupil, in colloquial Arabic."],
  "creator_ssim": ["Me and Frederick"],
  "creator_tesim": ["Me and Frederick"],
  "alternativeTitle_tesim": ["Book of Sindbad.",
                             "Sindbad the sailor"],
  "child_oids_ssim": ["11",
                      "12",
                      "13",
                      "14",
                      "15"],
  "collectionId_ssim": ["1"],
  "collectionId_tesim": ["1"],
  "contents_tesim": ["A few leaves supplied in a later hand.",
                     "Fair modern (18th century?) naskhī, in red and black.",
                     "Islamic binding, paper covered, with flap."],
  "date_ssim": ["[17--?]"],
  "dateStructured_ssim": ["1700"],
  "dependentUris_ssim": ["/ladybird/oid/11607445"],
  "description_tesim": ["A few leaves supplied in a later hand.",
                        "Fair modern (18th century?) naskhī, in red and black.",
                        "Islamic binding, paper covered, with flap."],
  "extent_ssim": ["81 leaves ; 20.5 x 14.5 cm."],
  "extentOfDigitization_ssim": ["Complete work digitized."],
  "format_tesim": ["mixed material"],
  "callNumber_ssim": ["Landberg MSS 596"],
  "callNumber_tesim": ["Landberg MSS 596"],
  "imageCount_isi": 85,
  "indexedBy_tsim": ["Brockelmann, S I, pp. 237, 239, 252."],
  "oid_ssi": "11607445",
  "orbisBibId_ssi": "3832098",
  "public_bsi": true,
  "recordType_ssi": "oid",
  "preferredCitation_tesim": ["Brockelmann, S I, pp. 237, 239, 252."],
  "repository_ssim": ["Beinecke Library"],
  "rights_ssim": ["The use of this image may be subject to the copyright law of the United States (Title 17, United States Code) or to site license or other rights management terms and conditions. The person using the image is liable for any infringement."],
  "rights_tesim": ["The use of this image may be subject to the copyright law of the United States (Title 17, United States Code) or to site license or other rights management terms and conditions. The person using the image is liable for any infringement."],
  "source_ssim": ["ladybird"],
  "subjectEra_ssim": ["Islamic binding"],
  "subjectTitle_tsim": ["Islamic binding"],
  "subjectTitleDisplay_tsim": ["Arabic language and literature--Belles lettres",
                               "Islamic binding"],
  "subjectName_ssim": ["Computer Science"],
  "subjectName_tesim": ["Computer Science"],
  "subjectTopic_tesim": ["Arabic language and literature--Belles lettres",
                         "Islamic binding"],
  "subjectTopic_ssim": ["Arabic language and literature--Belles lettres",
                        "Islamic binding"],
  "title_tesim": ["Record 1"],
  "title_ssim": ["Record 1"],
  "uri_ssim": ["/ladybird/oid/11607445"],
  "visibility_ssi": "Public",
  "orbisBibId_ssim": ["3832098"],
  "references_ssim": ["Brockelmann, S I, pp. 237, 239, 252."]
}.freeze

ADVANCED_SEARCH_TESTING_2 = {
  "id": "2",
  "abstract_tesim": ["Manuscript on parchment of Jacopo Zeno, Vita Caroli Zeni. With a dedicatory preface to Pope Pius II. This manuscript is of special importance because it contains the complete work."],
  "creator_ssim": ["Zeno, Jacopo, 1417-1481"],
  "creator_tesim": ["Zeno, Jacopo, 1417-1481"],
  "collectionId_ssim": ["1"],
  "collectionId_tesim": ["1"],
  "contents_tesim": ["Binding: Eighteenth century. Brownish-red goatskin, gold-tooled; pale green and gold, Dutch gilt paper boards.",
                     "On f. 1r, a foliage border which includes hares, stork, vase, and arms of the Piccolomini family (argent, a cross azur with 5 crescents or; surmounted by keys in saltire argent and a papal tiara; supported by a pair of angels). Eleven elaborate initials, 11- to 7-line, in gold, red, blue, and green entwined with foliage. The style of decoration is decidedly Roman.",
                     "Purchased by William Loring Andrews who presented it to Yale in 1894.",
                     "Script: Written in humanistic script by Franciscus de Tianis of Pistoia."],
  "contributor_tsim": ["Zeno, Carlo,--1334-1418",
                       "Zeno, Jacopo,--1417-1481"],
  "contributorDisplay_tsim": ["Zeno, Carlo,--1334-1418",
                              "Zeno, Jacopo,--1417-1481"],
  "creatorDisplay_tsim": ["Zeno, Jacopo, 1417-1481"],
  "child_oids_ssim": ["20",
                      "21",
                      "23",
                      "24"],
  "dateStructured_ssim": ["1458"],
  "dependentUris_ssim": ["/ladybird/oid/11684565"],
  "description_tesim": ["Binding: Eighteenth century. Brownish-red goatskin, gold-tooled; pale green and gold, Dutch gilt paper boards.",
                        "On f. 1r, a foliage border which includes hares, stork, vase, and arms of the Piccolomini family (argent, a cross azur with 5 crescents or; surmounted by keys in saltire argent and a papal tiara; supported by a pair of angels). Eleven elaborate initials, 11- to 7-line, in gold, red, blue, and green entwined with foliage. The style of decoration is decidedly Roman.",
                        "Purchased by William Loring Andrews who presented it to Yale in 1894.",
                        "Script: Written in humanistic script by Franciscus de Tianis of Pistoia."],
  "extent_ssim": ["ff. ii + 192 + i : parchment ; 271 x 177 (177 x 106) mm."],
  "extentOfDigitization_ssim": ["Complete work digitized."],
  "genre_tesim": ["Decorated initials",
                  "Manuscripts"],
  "callNumber_ssim": ["Beinecke MS 2"],
  "callNumber_tesim": ["Beinecke MS 2"],
  "imageCount_isi": 398,
  "indexedBy_tsim": ["Jacopo Zeno, Vita Caroli Zeni. General Collection, Beinecke Rare Book and Manuscript Library, Yale University.",
                     "Shailor, B. Catalogue of Medieval and Renaissance Manuscripts in the Beinecke Rare Book and Manuscript Library, MS 2."],
  "language_ssim": ["Latin"],
  "oid_ssi": "11684565",
  "orbisBibId_ssi": "9801995",
  "public_bsi": true,
  "creationPlace_ssim": ["Italy,"],
  "creationPlace_tesim": ["Italy,"],
  "recordType_ssi": "oid",
  "preferredCitation_tesim": ["Jacopo Zeno, Vita Caroli Zeni. General Collection, Beinecke Rare Book and Manuscript Library, Yale University.",
                              "Shailor, B. Catalogue of Medieval and Renaissance Manuscripts in the Beinecke Rare Book and Manuscript Library, MS 2."],
  "repository_ssim": ["Beinecke Library"],
  "resourceType_ssim": ["Archives or Manuscripts"],
  "resourceType_tesim": ["Archives or Manuscripts"],
  "rights_ssim": ["The use of this image may be subject to the copyright law of the United States (Title 17, United States Code) or to site license or other rights management terms and conditions. The person using the image is liable for any infringement."],
  "rights_tesim": ["The use of this image may be subject to the copyright law of the United States (Title 17, United States Code) or to site license or other rights management terms and conditions. The person using the image is liable for any infringement."],
  "source_ssim": ["ladybird"],
  "subjectEra_ssim": ["Medieval and Renaissance Manuscripts in Beinecke Library"],
  "subjectTitle_tsim": ["Medieval and Renaissance Manuscripts in Beinecke Library"],
  "subjectTitleDisplay_tsim": ["Biography--Middle Ages, 500-1500",
                               "Crusades--13th-15th centuries",
                               "Illumination of books and manuscripts, Medieval",
                               "Manuscripts, Medieval--Connecticut--New Haven",
                               "Medieval and Renaissance Manuscripts in Beinecke Library"],
  "subjectName_ssim": ["Zeno, Carlo,--1334-1418",
                       "Zeno, Jacopo,--1417-1481"],
  "subjectName_tesim": ["Zeno, Carlo,--1334-1418",
                        "Zeno, Jacopo,--1417-1481"],
  "subjectTopic_tesim": ["Biography--Middle Ages, 500-1500",
                         "Crusades--13th-15th centuries",
                         "Illumination of books and manuscripts, Medieval",
                         "Manuscripts, Medieval--Connecticut--New Haven",
                         "Medieval and Renaissance Manuscripts in Beinecke Library"],
  "subjectTopic_ssim": ["Biography--Middle Ages, 500-1500",
                        "Crusades--13th-15th centuries",
                        "Illumination of books and manuscripts, Medieval",
                        "Manuscripts, Medieval--Connecticut--New Haven",
                        "Medieval and Renaissance Manuscripts in Beinecke Library"],
  "title_tesim": ["Record 2"],
  "uri_ssim": ["/ladybird/oid/11684565"],
  "url_suppl_ssim": ["https://pre1600ms.beinecke.library.yale.edu/docs/pre1600.ms002.htm"],
  "visibility_ssi": "Public",
  "orbisBarcode_ssim": ["39002091594300"],
  "orbisBibId_ssim": ["9801995"],
  "references_ssim": ["Jacopo Zeno, Vita Caroli Zeni. General Collection, Beinecke Rare Book and Manuscript Library, Yale University.",
                      "Shailor, B. Catalogue of Medieval and Renaissance Manuscripts in the Beinecke Rare Book and Manuscript Library, MS 2."]

}.freeze
