# frozen_string_literal: true
WORK_WITH_ALL_FIELDS = {
  id: '111',
  title_tesim: "Diversity Bull Dogs",
  subtitle_tesim: "He's handsome",
  subtitle_vern_ssim: "He's handsome",
  creator_ssim: ['Frederick,  Eric & Maggie'],
  format: 'three dimensional object',
  url_fulltext_ssim: 'http://0.0.0.0:3000/catalog/111',
  url_suppl_ssim: 'http://0.0.0.0:3000/catalog/111',
  published_ssim: "1997",
  language_ssim: ['en', 'eng', 'zz'],
  isbn_ssim: '2321321389',
  description_tesim: "Handsome Dan is a bulldog who serves as Yale Univeristy's mascot.",
  visibility_ssi: 'Public',
  abstract_tesim: "this is an abstract",
  alternativeTitle_tesim: "this is an alternative title",
  genre_ssim: ["this is the genre", "this is the second genre"],
  subjectGeographic_ssim: ['this is the geo subject', 'these are the geo subjects'],
  subjectGeographic_tesim: "this is the geo subject",
  resourceType_ssim: "this is the resource type",
  subjectName_ssim: "this is the subject name",
  subjectTopic_tesim: "this is the subject topic",
  subjectTopic_ssim: "this is also the subject topic",
  extentOfDigitization_ssim: 'this is the extent of digitization',
  rights_ssim: "these are the rights",
  creationPlace_ssim: "this is the publication place",
  sourceCreated_tesim: "this is the source created",
  publisher_ssim: "this is the publisher",
  copyrightDate_ssim: "this is the copyright date",
  source_ssim: "this is the source",
  recordType_ssi: "this is the record type",
  sourceTitle_tesim: "this is the source title",
  sourceCreator_tesim: "this is the source creator",
  sourceDate_tesim: "this is the source date",
  sourceNote_tesim: "this is the source note",
  sourceEdition_tesim: 'Source Edition',
  preferredCitation_tesim: "these are the references",
  date_ssim: "this is the date",
  children_ssim: "these are the children",
  importUrl_ssim: "this is the import URL",
  oid_ssi: '2345678',
  identifierMfhd_ssim: 'this is the identifier MFHD',
  containerGrouping_tesim: 'this is the container information',
  callNumber_ssim: 'this is the call number',
  orbisBibId_ssi: '1234567',
  findingAid_ssim: 'this is the finding aid',
  edition_ssim: 'this is the edition',
  numberOfPages_ssim: "this is the number of pages, using ssim",
  material_tesim: "this is the material, using ssim",
  scale_tesim: "this is the scale, using ssim",
  digital_ssim: "this is the digital, using ssim",
  coordinates_ssim: "this is the coordinates, using ssim",
  projection_tesim: "this is the projection, using ssim",
  extent_ssim: "this is the extent, using ssim"
}.freeze
