# frozen_string_literal: true
WORK_WITH_PUBLIC_VISIBILITY = {
  "id": "2055095",
  "title_tesim": ["A General dictionary of the English language"],
  "creator_tesim": ["Johnson, Samuel, 1709-1784"],
  "extent_ssim": ["1 volume",
                  "43 cm."],
  "format": ["text"],
  "language_ssim": ["English"],
  "description_tesim": ["Four volume printer's proof with manuscript notes throughout."],
  "abstract_tesim": ["Published on April 15, 1755 and written largely single-handedly by Samuel Johnson. Sometimes published as \"Johnson's Dictionary.\" The first edition was published in two folio volumes; later editions were published in four volumes."],
  "genre_ssim": ["Annotations",
                 "Dictionaries",
                 "Marginalia",
                 "Proofs (Printed matter)"],
  "resourceType_ssim": ["Books, Journals & Pamphlets"],
  "extentOfDigitization_ssim": ["Complete work digitized."],
  "rights_ssim": ["The use of this image may be subject to the copyright law of the United States (Title 17, United States Code) or to site license or other rights management terms and conditions. The person using the image is liable for any infringement."],
  "creationPlace_ssim": ["London"],
  "publisher_ssim": ["Printed by W. Strahan, for J. and P. Knapton [etc.]"],
  "source_ssim": ["ladybird"],
  "recordType_ssi": ["oid"],
  "dateStructured_ssim": ["1755"],
  "oid_ssi": ["2055095"],
  "callNumber_ssim": ["GEN MSS VOL 728 (Oversize)"],
  "containerGrouping_ssim": ["GEN MSS VOL 728 (Oversize)"],
  "orbisBibId_ssi": ["1169354"],
  "uri_ssim": ["/ladybird/oid/2055095"],
  "partOf_ssim": ["Beinecke Library"],
  "number_of_pages_ss": "Vol. 3",
  "date_ssim": ["1755"],
  "public_bsi": true,
  "visibility_ssi": "Public"
}.freeze

WORK_WITH_PRIVATE_VISIBILITY = {
  "id": "16189097-priv",
  "title_tesim": ["[Map of China]. [private copy]"],
  "extent_ssim": ["1 map ; folded in covers 25 x 16 cm."],
  "format": ["cartographic"],
  "language_ssim": ["Japanese"],
  "description_tesim": ["In Japanese.",
                        "Japanese reprint of a Chinese map published in 1663.",
                        "Transliteration supplied by cataloger."],
  "genre_ssim": ["Maps."],
  "resourceType_ssim": ["Maps, Atlases & Globes"],
  "extentOfDigitization_ssim": ["Complete work digitized."],
  "rights_ssim": ["The use of this image may be subject to the copyright law of the United States (Title 17, United States Code) or to site license or other rights management terms and conditions. The person using the image is liable for any infringement."],
  "creationPlace_ssim": ["Kyoto [Japan] :"],
  "publisher_ssim": ["Umemura Yahaku,"],
  "source_ssim": ["ladybird"],
  "recordType_ssi": ["oid"],
  "illustrativeMatter_tesim": "080815s189u    ja ",
  "oid_ssi": ["16189097-priv"],
  "callNumber_ssim": ["Lanman Covers 56 189x"],
  "containerGrouping_ssim": ["Lanman Covers 56 189x"],
  "orbisBibId_ssi": ["8330740"],
  "uri_ssim": ["/ladybird/oid/16189097-priv"],
  "partOf_ssim": ["Beinecke Library"],
  "scale_tesim": ["Scale not given."],
  "coordinates_ssim": ["a"],
  "date_ssim": ["[189x?]"],
  "public_bsi": true,
  "visibility_ssi": "Private"
}.freeze

WORK_WITH_YALE_ONLY_VISIBILITY = {
  "id": "16189097-yale",
  "title_tesim": ["[Map of China]. [yale-only copy]"],
  "extent_ssim": ["1 map ; folded in covers 25 x 16 cm."],
  "format": ["cartographic"],
  "language_ssim": ["Japanese"],
  "description_tesim": ["In Japanese.",
                        "Japanese reprint of a Chinese map published in 1663.",
                        "Transliteration supplied by cataloger."],
  "genre_ssim": ["Maps."],
  "resourceType_ssim": ["Maps, Atlases & Globes"],
  "extentOfDigitization_ssim": ["Complete work digitized."],
  "rights_ssim": ["The use of this image may be subject to the copyright law of the United States (Title 17, United States Code) or to site license or other rights management terms and conditions. The person using the image is liable for any infringement."],
  "creationPlace_ssim": ["Kyoto [Japan] :"],
  "publisher_ssim": ["Umemura Yahaku,"],
  "source_ssim": ["ladybird"],
  "recordType_ssi": ["oid"],
  "illustrativeMatter_tesim": "080815s189u    ja ",
  "oid_ssi": ["16189097-yale"],
  "callNumber_ssim": ["Lanman Covers 56 189x"],
  "containerGrouping_ssim": ["Lanman Covers 56 189x"],
  "orbisBibId_ssi": ["8330740"],
  "uri_ssim": ["/ladybird/oid/16189097"],
  "partOf_ssim": ["Beinecke Library"],
  "scale_tesim": ["Scale not given."],
  "coordinates_ssim": ["a"],
  "date_ssim": ["[189x?]"],
  "public_bsi": true,
  "visibility_ssi": "Yale Community Only"
}.freeze
